language: c

sudo: required

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
      compiler: clang
    - os: windows
      compiler: x86_64-w64-mingw32-gcc
      env: PACKAGES="gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64 mingw-w64-dev"

git:
  depth: 5


before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux"   ]; then ./travis/linux-before.sh;   fi
  - if [ "$TRAVIS_OS_NAME" = "osx"     ]; then ./travis/osx-before.sh;     fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ./travis/windows-before.sh; fi

script:
  - if [ "$TRAVIS_OS_NAME" = "linux"   ]; then PKG_CONFIG_PATH="$(pwd)/TRAVIS_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH" CFLAGS="-I/usr/include/freetype2" make; fi
  - if [ "$TRAVIS_OS_NAME" = "osx"     ]; then make -f src/cocoa/Makefile utox; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then make dist; fi

notifications:
  email: false
