language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./travis/linux-before.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./travis/osx-before.sh; fi

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then CFLAGS="-I/usr/include/freetype2" make; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make -f cocoa/Makefile utox; fi

notifications:
  email: false
