language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

sudo: required

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./travis/linux-before.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./travis/osx-before.sh; fi

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then PKG_CONFIG_PATH="$(pwd)/TRAVIS_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH" CFLAGS="-I/usr/include/freetype2" make; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make -f src/cocoa/Makefile utox; fi

notifications:
  email: false
