language: c
compiler:
  - gcc
  - clang

sudo: false

addons:
  apt:
    packages:
    - yasm
    - check
    - libsodium
    - libopus
    - libvpx2

before_script:
  #installing libconfig, needed for DHT_bootstrap_daemon
  - wget http://www.hyperrealm.com/libconfig/libconfig-1.4.9.tar.gz > /dev/null
  - tar -xvzf libconfig-1.4.9.tar.gz > /dev/null
  - cd libconfig-1.4.9
  - ./configure --prefix=$HOME/libconfig > /dev/null
  - make -j3 > /dev/null
  - make install > /dev/null
  - cd ..
  #installing toxcore, so THEN we can compile utox...
  - git clone https://github.com/irungentoo/toxcore
  - cd toxcore
  - ./autogen.sh
  - ./configure --prefix=$HOME/toxcore --disable-ntox --disable-tests --disable-testing --with-dependency-search="$HOME" --with-libsodium-headers=$HOME/libsodium --with-libsodium-libs=$HOME/libsodium/libs --disable-shared --enable-static
  - make -j3 >/dev/null
  - make install
  - cd ..

script:
  - make

notifications:
  email: false

  irc:
    channels:
      - "chat.freenode.net#tox-dev"
    on_success: always
    on_failure: always
