language: c

addons:
  apt:
    packages:
      - yasm
      - check
      - libopenal-dev
      - libdbus-1
      - libv4l-dev
      - gcc-mingw-w64
      - gcc-mingw-w64-base
      - mingw-w64
      - mingw-w64-common
      - mingw-w64-dev
      - binutils-mingw-w64

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD=linux
    - os: linux
      compiler: clang
      env: BUILD=linux
    - os: osx
      compiler: clang
      env: BUILD=osx
    - os: windows
      compiler: x86_64-w64-mingw32-gcc
      env: BUILD=windows

git:
  depth: 5


before_script:
  - if [ "$BUILD" = "linux"   ]; then ./travis/linux-before.sh;   fi
  - if [ "$BUILD" = "osx"     ]; then ./travis/osx-before.sh;     fi
  - if [ "$BUILD" = "windows" ]; then ./travis/windows-before.sh; fi

script:
  - if [ "$BUILD" = "linux"   ]; then PKG_CONFIG_PATH="$(pwd)/TRAVIS_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH" CFLAGS="-I/usr/include/freetype2" make; fi
  - if [ "$BUILD" = "osx"     ]; then make -f src/cocoa/Makefile utox; fi
  - if [ "$BUILD" = "windows" ]; then make dist; fi

notifications:
  email: false
